flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/AeonikBold.ttf
          weight: 700
        - asset: assets/fonts/AeonikRegular.ttf
          weight: 400
        - asset: assets/fonts/AeonikMedium.ttf
          weight: 500
